from marshmallow import Schema, fields
from schemas.create_measurements_schema import CreateMeasurements
from schemas.get_measurements_schema import GetMeasurements
from schemas.get_range_measurements_schema import GetRangeMeasurements